insert into developers (name, is_active, sort_order)
values
  ('Alveo Land', true, 130),
  ('Avida Land', true, 140),
  ('Amaia Land', true, 150),
  ('Bellavita Land', true, 160),
  ('Empire East Land Holdings', true, 170),
  ('Anchor Land', true, 180),
  ('Shang Properties', true, 190),
  ('Century Properties', true, 200),
  ('Eton Properties Philippines', true, 210),
  ('Landco Pacific Corporation', true, 220),
  ('Arthaland', true, 230),
  ('Greenfield Development Corporation', true, 240),
  ('Sta. Lucia Land', true, 250),
  ('Cebu Landmasters', true, 260),
  ('Damosa Land', true, 270),
  ('AppleOne Properties', true, 280),
  ('Suntrust Properties', true, 290),
  ('Pueblo de Oro Development Corporation', true, 300),
  ('Johndorf Ventures Corporation', true, 310),
  ('NorthPine Land', true, 320),
  ('Property Company of Friends (Pro-Friends)', true, 330),
  ('Phirst Park Homes', true, 340),
  ('Ovialand', true, 350),
  ('Hausland Development Corporation', true, 360),
  ('PrimaryHomes', true, 370),
  ('Grand Land', true, 380),
  ('Paramount Property Ventures', true, 390),
  ('P.A. Properties Hankyu Hanshin', true, 400),
  ('Xavier Estates', true, 410),
  ('Crown Asia', true, 420),
  ('Brittany Corporation', true, 430),
  ('Vista Residences', true, 440),
  ('Camella Manors', true, 450),
  ('Cityland', true, 460),
  ('Primex Realty Corporation', true, 470),
  ('Torre Lorenzo Development Corporation', true, 480),
  ('Phinma Properties', true, 490),
  ('Wee Community Developers', true, 500),
  ('New San Jose Builders', true, 510),
  ('8990 Holdings', true, 520)
on conflict (name) do update
set
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  updated_at = now();
